version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: ["./docker-entrypoint.sh"]
    #command: python manage.py runserver 0.0.0.0:8000
    #    environment:
    #      - DJANGO_SETTINGS_MODULE=devops.settings
    #    volumes:
    #        - .:/code
    #      - ./docker-entrypoint.sh:/docker-entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
